version: "3.8"

services:
 las2peer-getweather:
  build: .
  ports:
   - 8888:8888
  environment:
   - GETWEATHER_APPID=<APP_ID>
 nginx:
  image: "nginx:alpine"
  ports:
   - 80:80
  volumes:
   - ./frontEnd:/usr/share/nginx/html
  restart: unless-stopped